In [1]:
import pandas as pd
from langdetect import detect
from SPARQLWrapper import SPARQLWrapper, JSON
import re
import numpy as np
import sys
import os
import time
from nltk.tag import pos_tag
import urllib.parse

In [2]:
target = pd.read_csv("D:\Dokumenty\Zastosowanie Technologii Informatycznych\data\CEA_Round1_Targets.csv",
                    sep = ',',
                     skiprows=range(112,113), # 112 wadliwy wiersz
                    names=['TableID', 'ColumnID', 'RowID'])
target[:3]

                          TableID  ColumnID  RowID
0   50245608_0_871275842592178099         0    154
1  39107734_2_2329160387535788734         1     32
2  22864497_0_8632623712684511496         0    227

In [8]:
tables_ids = target['TableID'].unique()

In [13]:
for table_id in tables_ids:
        df = pd.read_csv(f"D:\Dokumenty\Zastosowanie Technologii Informatycznych\data\CEA_Round1\{table_id}.csv",
                sep=',')
        print(table_id)
        print(df.columns)

50245608_0_871275842592178099
Index(['Title', 'Year', 'Media Type', 'Director', 'Writer', 'Length',
       'Matting'],
      dtype='object')
39107734_2_2329160387535788734
Index(['Rank', 'Airport', 'Location', 'Code (IATA/ICAO)', 'Total Passengers',
       'Rank Change', '% Change'],
      dtype='object')
22864497_0_8632623712684511496
Index(['Title', 'Publisher', 'North America', 'Europe', 'Japan', 'Cost',
       'Size'],
      dtype='object')
66009064_0_9148652238372261251
Index(['???O', '???[?O', '?`?[??', '????', '?N', '??'], dtype='object')
21362676_0_6854186738074119688
Index(['Fans' Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
40534006_0_4617468856744635526
Index(['#', 'Catcheur', 'Nombre de r?gnes', 'Jours combin?s'], dtype='object')
36102169_0_7739454799295072814
Index(['Platform', 'Developer', 'Game Title', 'Units Sold (in millions)'], dtype='object')
53822652_0_5767892317858575530
Index(['Date', 'Movie', 'Year', 'Director'], dtype='object')
60319454_0_3938426910282115527
Index(['English name', 'Latin name', 'Hungarian name'], dtype='object')
8468806_0_4382447409703007384
Index(['Rang', 'Name', 'Staat(en)', 'Fläche-(km2)', 'Länge-(km)',
       'Max.-Tiefe-(m)', 'Volumen-(km?)'],
      dtype='object')
33401079_0_9127583903019856402
Index(['Adam av Bremen', '1040?85', 'Historieskriver'], dtype='object')
99070098_0_2074872741302696997
Index(['No.', 'Name', 'Feet', 'Met', 'Grid Ref', 'Area', '?', 'Trips'], dtype='object')
50270082_0_444360818941411589
Index(['Rank', 'Player (2011 Ws)', 'W'], dtype='object')
29414811_12_251152470253168163
Index(['Year', 'Game', 'Genre', 'Platform(s)', 'Developer(s)'], dtype='object')
39759273_0_1427898308030295194
Index(['N', 'Title', 'Year', 'Director', 'IMDB Rating', 'IMDB Votes'], dtype='object')
69537082_0_7789694313271016902
Index(['Rank', 'Country', 'Population', 'Date of Information'], dtype='object')
88523363_0_8180214313099580515
Index(['Scientific Name', 'Common Names (abridged)', 'Family', 'Habit'], dtype='object')
41480166_0_6681239260286218499
Index(['Saint', 'Anglican', 'Ethiopian', 'Orthodox', 'Catholic',
       'Non-historical'],
      dtype='object')
9834884_0_3871985887467090123
Index(['Nr.', 'Museum', 'Country', 'Score *'], dtype='object')
26310680_0_5150772059999313798
Index(['ENTITY', 'CURRENCY', 'ALPHABETIC CODE', 'NUMERIC CODE'], dtype='object')
39173938_0_7916056990138658530
Index(['Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
91959037_0_7907661684242014480
Index(['#', 'Titel', 'System', 'Reviews', 'Durchschnitt'], dtype='object')
13719111_1_5719401842463579519
Index(['Animal English', 'Animal latin', 'Description'], dtype='object')
54719588_0_8417197176086756912
Index(['Sequence', 'Date', 'New?', 'Title', 'Country', 'Director', 'Year',
       'Grade', 'Theater', 'Shorts', 'Additional Info', 'Ignore This',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')
58891288_0_1117541047012405958
Index(['Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
28086084_0_3127660530989916727
Index(['Saint', 'Anglican', 'Ethiopian', 'Orthodox', 'Catholic',
       'Non-historical'],
      dtype='object')
21245481_0_8730460088443117515
Index(['State/Province', 'Lake Name', 'File Size'], dtype='object')
90196673_0_5458330029110291950
Index(['Common Name', 'Scientific Name', 'Season'], dtype='object')
35188621_0_6058553107571275232
Index(['Fans' Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
46671561_0_6122315295162029872
Index(['Game', 'Genre', 'Platform', 'Release'], dtype='object')
25404227_0_2240631045609013057
Index(['Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
63450419_0_8012592961815711786
Index(['Abbreviation', 'Species', 'Common Name'], dtype='object')
29414811_2_4773219892816395776
Index(['Year', 'Game', 'Genre', 'Platform(s)', 'Developer(s)'], dtype='object')
20135078_0_7570343137119682530
Index(['Fans' Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
39650055_5_7135804139753401681
Index(['Rank', 'Brand', 'Value', 'Industry'], dtype='object')
16767252_0_2409448375013995751
Index(['Fans' Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
9475172_1_1023126399856690702
Index(['U.S./Canada Release Date', 'Title', 'Season #', 'Notes'], dtype='object')
24036779_0_5608105867560183058
Index(['Country', 'Land area (km2) [49]', 'GDP nominal (US$M)[50]',
       'Per capita GDP (US$)[51]', 'Population[52]', 'Government[53]',
       'Conscription[54]'],
      dtype='object')
69881946_0_1105130426898457358
Index(['Fans' Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
75367212_2_2745466355267233390
Index(['Title', 'Developer(s)', 'Publisher(s)', 'Release Date', 'ESRB'], dtype='object')
84575189_0_6365692015941409487
Index(['#', 'Citations', 'Journal'], dtype='object')
84548468_0_5955155464119382182
Index(['Fans' Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
52299421_0_4473286348258170200
Index(['Unnamed: 0', '1998 Data Country', 'GDP Per Capita', 'GDP Growth Rate',
       'GDP', 'Inflation', 'Population', 'Popul. Growth', 'Infant Mortality'],
      dtype='object')
37856682_0_6818907050314633217
Index(['State, Province, Territory, Country, etc', 'Area (square miles)',
       'Comments'],
      dtype='object')
38428277_0_1311643810102462607
Index(['Fans' Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
41336118_0_4331895026409635103
Index(['Company', 'Country', 'Industry', 'Sales ($bil)', 'Profits ($bil)',
       'Assets ($bil)', 'Market Value ($bil)'],
      dtype='object')
71840765_0_6664391841933033844
Index(['Lake', 'water temperature', 'water gauge'], dtype='object')
77694908_0_6083291340991074532
Index(['Fans' Rank', 'Title', 'Year', 'Director(s)', 'Overall Rank'], dtype='object')
43237185_1_3636357855502246981
Index(['Mathematician', 'Year of PhD', 'Granting Institution', 'Supervisor',
       'Thesis'],
      dtype='object')
45073662_0_3179937335063201739
Index(['Rank', 'Player (2011 TBs)', 'TBs'], dtype='object')
11833461_1_3811022039809817402
Index(['Title', 'Publisher', 'EU Release Date', 'AU Release Date', 'PEGI',
       'ACB'],
      dtype='object')
14067031_0_559833072073397908
Index(['OAU State', 'Official Language', 'IMF SDRs', 'Date of Independence',
       'Head of Central Bank', 'Capital', 'IMF #Votes', 'Name of Currency'],
      dtype='object')
9567241_0_5666388268510912770
Index(['#', 'Media', 'MIX'], dtype='object')
34041816_1_4749054164534706977
Index(['Rank', 'Airport', 'Location', 'Code (IATA)', 'Total Passengers',
       '% Change'],
      dtype='object')
10579449_0_1681126353774891032
Index(['#', 'Media', 'MIX'], dtype='object')
14380604_4_3329235705746762392
Index(['Rank', 'Company', 'Headquarters', 'Industry', 'Revenue (billion $)',
       'Profits (billion $)', 'Assets (billion $)',
       'Market Value (billion $)'],
      dtype='object')
29414811_13_8724394428539174350
Index(['Year', 'Game', 'Genre', 'Platform(s)', 'Developer(s)'], dtype='object')
80588006_0_6965325215443683359
Index(['#', 'Media', 'MIX'], dtype='object')
1438042989018_40_20150728002309-00067-ip-10-236-191-2_57714692_2
Index(['Worcestershire bowling', 'Overs', 'Mdns', 'Runs', 'Wkts', 'Wides',
       'No-Balls'],
      dtype='object')
1438042986423_95_20150728002306-00125-ip-10-236-191-2_88435628_5
Index(['Party', 'Votes 2015', '% votes 2015', 'Seats',
       'Poll standing 16/4/15'],
      dtype='object')
29414811_6_8221428333921653560
Index(['Year', 'Game', 'Genre', 'Platform(s)', 'Developer(s)'], dtype='object')
53989675_0_8697482470743954630
Index(['Lake Name', 'Access', 'Acres', 'Class', 'Category'], dtype='object')
1438042986423_95_20150728002306-00329-ip-10-236-191-2_805336391_10
Index(['#', 'Name', 'Age', 'Club', 'LMSC', 'Time'], dtype='object')
1438042989043_35_20150728002309-00287-ip-10-236-191-2_875026214_2
Index(['Summit', 'Location', 'Elevation'], dtype='object')

In [ ]:
33401079_0_9127583903019856402
41480166_0_6681239260286218499 ?
52299421_0_4473286348258170200 ?